/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
 import { Asset } from "expo-asset";
import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera, useTexture } from '@react-three/drei/native'
import Model from '../../assets/models/gob.glb'

export default function ObjectLoad(props) {
  let { nodes, materials } = useGLTF(Model)
  
// const textureAsset = Asset.fromModule(require('../../assets/images/texture.jpeg')).uri;
// const texture = useTexture(textureAsset);
// texture.flipY = false;

  // const texture = useTexture(require('../../assets/images/texture.jpeg'))

 
  return (
         <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BrasD.geometry}
        material={materials.Peau}
        position={[0.949, 1.831, 0]}
        rotation={[0, 0, 1.55]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MainD.geometry}
        material={materials.Peau}
        position={[2.104, 1.818, 0]}
        rotation={[0, 0, -1.584]}
        scale={[0.219, 0.265, 0.265]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MainG.geometry}
        material={materials.Peau}
        position={[-2.072, 1.878, 0]}
        rotation={[0, 0, -1.584]}
        scale={[0.219, 0.265, 0.265]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Nez.geometry}
        material={materials['Nez.001']}
        position={[0.001, 2.741, -0.757]}
        scale={0.196}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Corps.geometry}
        material={materials.Peau}
        position={[0.024, 1.34, 0.003]}
        scale={[0.746, 0.802, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tete002.geometry}
        material={materials.Peau}
        position={[0, 2.828, 0.052]}
        scale={[1, 0.694, 0.793]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BrasG.geometry}
        material={materials.Peau}
        position={[-0.901, 1.866, 0]}
        rotation={[0, 0, 1.552]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PiedD001.geometry}
        material={materials.Peau}
        position={[-0.323, -0.291, 0]}
        rotation={[0, 0, 3.128]}
        scale={[0.899, 1.611, 1.057]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PiedG001.geometry}
        material={materials.Peau}
        position={[0.339, -0.288, 0]}
        rotation={[0, 0, 3.128]}
        scale={[0.945, 1.618, 1.057]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bagne.geometry}
        material={materials.Slip}
        position={[0.004, 0.562, -0.15]}
        scale={[0.676, 0.439, 0.676]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bagne_dessus.geometry}
        material={materials.BoutdeSlip}
        position={[0.026, 0.842, 0]}
        scale={[0.667, 0.226, 0.667]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cheveux7.geometry}
        material={materials.Cheveux}
        position={[0, 2.828, 0.052]}
        scale={[1, 0.694, 0.793]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.OeilG.geometry}
        material={materials.oeil}
        position={[-0.328, 2.741, -0.659]}
        scale={0.096}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.OeilD.geometry}
        material={materials.oeil}
        position={[0.333, 2.741, -0.659]}
        scale={0.096}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bouche.geometry}
        material={materials['Material.002']}
        position={[-0.005, 2.498, -0.636]}
        rotation={[0, 0, 1.569]}
        scale={[0.017, 0.413, 0.017]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Dent.geometry}
        material={nodes.Dent.material}
        position={[-0.291, 2.498, -0.606]}
        scale={[0.059, 0.108, 0.023]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SourcilD.geometry}
        material={materials.Cheveux}
        position={[0.325, 3.024, -0.691]}
        rotation={[-Math.PI, 0, 1.572]}
        scale={[-0.061, -0.191, -0.061]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SourcilG.geometry}
        material={materials.Cheveux}
        position={[-0.29, 3.024, -0.691]}
        rotation={[0, 0, 1.569]}
        scale={[0.061, 0.194, 0.061]}
      />
    </group>
  )
}

useGLTF.preload(Model)

 
// import { useEffect } from "react";
// import { Asset } from "expo-asset";
// import { useGLTF, useTexture } from "@react-three/drei/native";
// import * as THREE from "three";
// import Model from "../../assets/models/Duck.glb"

// export default function ObjectLoad() {
 
//   const cheeseTexture = useTexture(
//     require("../../assets/images/texture.jpeg")
//   );

//   const gltf = useGLTF(Model);

//   // Apply custom texture to all meshes
//   useEffect(() => {
//     if (!gltf.scene) return;

//     gltf.scene.traverse((obj) => {
//       if (obj.isMesh) {
//         obj.material = new THREE.MeshStandardMaterial({
//           map: cheeseTexture,
//         });
//         obj.castShadow = true;
//         obj.receiveShadow = true;
//       }
//     });
//   }, [gltf.scene, cheeseTexture]);

//   return (
//     <mesh>
//       <primitive position={[0, 0, 0]} object={gltf.scene} scale={1} />
//     </mesh>
//   );
// }

 